### ISSUE TITLE
macos.os missing on on OS X

### ISSUE THREAD

**Issue by haiduc32** [lucassklp/Desktop.Robot#2]
Hi,

I've stumbled onto that problem when running on OS X. Apparently the nuget might not be configured correctly. I Copied the macos.os manually into my folder and it worked ok.

Here is the exception:

Exception has occurred: CLR/System.DllNotFoundException
An unhandled exception of type 'System.DllNotFoundException' occurred in Desktop.Robot.dll: 'Unable to load shared library './macos.os' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(./macos.os, 1): image not found'
   at Desktop.Robot.OSX.Robot.setMousePosition(UInt32 x, UInt32 y)
   at Desktop.Robot.OSX.Robot.MouseMove(UInt32 x, UInt32 y)
   at Desktop.Robot.Robot.MouseMove(UInt32 x, UInt32 y)
   at WSJTBuddy.Program.Main(String[] args) in /Users/macbookpro/Documents/DevMac/WSJTBuddy/Program.cs:line 14

**Comment by lucassklp** [comment]
Oh I see...

I think I need to include it when packaging the solution.
Thank you for reporting it =)
