### ISSUE TITLE
Linux: "x11.os" missing.

### ISSUE THREAD

**Issue by ProIntegritate** [lucassklp/Desktop.Robot#52]
So, found your project, looked interesting. I did the standard example with `robot.Type("Hello world!")` in a .NET 6 project. On Windows it works fine, but on Linux i get this message about "x11.os" missing:

_Unhandled exception. System.DllNotFoundException: Unable to load shared library './x11.os' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: ./x11.os: cannot open shared object file: No such file or directory
   at Desktop.Robot.Linux.Robot.pressKey(Char c, Boolean down, Int32 flags)
   at Desktop.Robot.Linux.Robot.KeyPress(Char key)
   at Desktop.Robot.Robot.KeyPress(Char key)
   at Desktop.Robot.Extensions.TypingExtension.Type(IRobot robot, String text)
   at dtr.Program.Main(String[] args)
Aborted (core dumped)_

**Yeah - the error is obvious**, but now How do i get the "x11.os" file? Do i have to compile it? Am i supposed to distribute it with the executable? Would it get included with a self contained distribution?

When i add the nuget package to my project, the only .os files i get are: "osx.os" and "osx_arm.os" - but not "x11.os" or anything like it when installing the nuget file (from nuget.org).

Thanks in advance.

**Comment by ProIntegritate** [comment]
Apparently, On Linux .Type() _only works in a web browser_ like Firefox and can't be used in a Terminal Window or other GUI application.

Also .KeyDown() .KeyPress(), .KeyUp() and .CombineKeys() does not work at all on Linux, only .Type() works meaning it is impossible to send ALT+TAB to flip between applications.

**Comment by olivercoad** [comment]
> Apparently, On Linux .Type() only works in a web browser like Firefox and can't be used in a Terminal Window or other GUI application.

`Type()` works fine for me in a Terminal Window and other GUI applications... what have you tried testing and what is your environment? Can you provide sample code to help reproduce your issue?

`KeyDown`/`KeyUp`/`CombineKeys` also do not work for me on linux. I never ended up getting around to adding unit tests for it in the TestApp, so for all I know perhaps they never worked on Linux.
`KeyPress`/`Type` do work for me though, and also have passing tests in the test app. @ProIntegritate could you please run the test app and paste the console output here? (Just cd into `Desktop.Robot.TestApp` then `dotnet run` and click the button. You should remove the "Can scroll vertical" test case from `MouseTests.fs:113` first though as it's currently failing by scrolling hundreds of times causing it to time out).

Also what is your desktop system info? Can you paste the ouput of `dotnet --info`?

**Comment by ProIntegritate** [comment]
The code is pretty much a copy paste of the example on the github page ( https://github.com/lucassklp/Desktop.Robot ) under the section "Example of use".  Basically i'm just using .Type() to get some output into the currently selected Window.

For this project I'm using .NET 8 and I'm using Ubuntu 22.04 (LTS) under VMWare Workstation, not sure if Gnome has something to do with it. Or VMWare.

Let me get back to you with more information.
